# Generated by Django 4.2.1 on 2023-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhalaAudio',
            fields=[
                ('studentId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('words', models.CharField(max_length=1000)),
            ],
        ),
    ]
